### ISSUE TITLE
Create Github action for documentation generation and deployment

### ISSUE THREAD

**Issue by bramvanhoutte** [kodiak-packages/ventura#6]

**Comment by RobinWijnant** [comment]
`yarn build` warns that tsconfig is outdated:
```
$ rm -rf dist && tsc -b -v && cpx './src/**/*.css' 'dist'
7:56:16 PM - Projects in this build: 
    * tsconfig.json

7:56:16 PM - Project 'tsconfig.json' is out of date because output file 'dist/src/index.js' does not exist

7:56:16 PM - Building project '/__w/ventura/ventura/tsconfig.json'...

Done in 9.54s.
```

Committing the generated docs fails:
```
Error: spawnSync /__w/_actions/EndBug/add-and-commit/v4/lib/entrypoint.sh ENOBUFS
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:607:24)
    at Object.execFileSync (child_process.js:634:15)
    at Object.131 (/__w/_actions/EndBug/add-and-commit/v4/lib/index.js:1:576)
    at __webpack_require__ (/__w/_actions/EndBug/add-and-commit/v4/lib/index.js:1:154)
    at startup (/__w/_actions/EndBug/add-and-commit/v4/lib/index.js:1:291)
    at module.exports.87 (/__w/_actions/EndBug/add-and-commit/v4/lib/index.js:1:323)
    at Object.<anonymous> (/__w/_actions/EndBug/add-and-commit/v4/lib/index.js:1:333)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```
